VIDEO 1 Edit->view('edit')->update(1) Delete->destroy(1)
VIDEO 2 Edit->view('edit')->update(2) Delete->destroy(2)
VIDEO 3 Edit->view('edit')->update(3) Delete->destroy(3)
VIDEO 4 Edit->view('edit')->update(4) Delete->destroy(4)
VIDEO 5 Edit->view('edit')->update(5) Delete->destroy(5)
VIDEO 6 Edit->view('edit')->update(6) Delete->destroy(6)
VIDEO 7 Edit->view('edit')->update(7) Delete->destroy(7)
